In [1]:
import numpy as np

# NumPy Program To Test Whether None Of The Elements Of A Given Array Is Zero.

In [8]:
v1 = np.array([[1,2,3,4,0]])
x = np.all(v1 != 0)
if x == False:
    x = "THE ARRAY INCLUDES ZERO"
    print(x)
else:
    x = "THE ARRAY DOES NOT INCLUDE ANY ZEROS"
    print(x)
    


THE ARRAY INCLUDES ZERO


# Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [26]:
v2 = np.array([[1,0,0,0,0]])
x = np.any(v2 != 0)
if x == False:
    x = "THE ARRAY DOES NOT INCLUDE NONE ZERO"
    print(x)
else:
    x = "THE ARRAY INCLUDES NONE ZEROS"
    print(x)

THE ARRAY INCLUDES NONE ZEROS


# Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given.

In [35]:
v1 = np.array([[10,20,30,40,50]])
v2 = np.array([[11,15,20,25,45]])

x = np.isclose(v1,v2,atol=5)

print(x)

print(v1[x])
print(v2[x])


[[ True  True False False  True]]
[10 20 50]
[11 15 45]


# Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives. 

In [41]:
v_zeros = np.zeros((3,3))
print(v_zeros)

print("--------------------")

v_ones = np.ones((3,3))
print(v_ones)

print("--------------------")

v_fives = np.full((3,3),5)
print(v_fives)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------
[[5 5 5]
 [5 5 5]
 [5 5 5]]


# Write a NumPy program to create an array of the integers from 30 to70.

In [66]:
v1 = np.arange(30, 71)
print(v1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# Write a NumPy program to create a 3x3 identity matrix.

In [69]:
v1 = np.eye(3)
print(v1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Write a NumPy program to generate a random number between 0 and 1.

In [72]:
v1 = np.random.rand(5)
print(v1)

[0.01798304 0.9417534  0.1574141  0.04632213 0.43635975]


# Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [73]:
v1 = np.random.randn(15)
print(v1)

[ 0.59360545  0.13244025  1.65681398 -0.83973807 -0.5700097   0.16408713
  0.4746512  -0.68900508 -0.298253    1.31883547 -0.53937855 -0.87292298
 -1.47168137  3.02448082  1.94542469]


# Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [74]:
v1 = np.arange(15, 56)
x = v1[1:-1]
print(x)

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.


In [75]:
v1 = np.random.randint(0,11,size=5)
print(v1)

[ 7 10  8  3  6]


# Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [81]:
m1 = np.ones((10, 10))

m1[1:-1 , 1:-1] = 0
print(m1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [84]:
m1 = np.zeros((5,5))
np.fill_diagonal(m1,(1,2,3,4,5))

print(m1)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [90]:
m1 = np.zeros((4, 4))

m1[::2 , 1::2] = 1
m1[1::2 , 0::2] = 1

m1

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

# Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it. 

In [93]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([6, 7, 8, 9, 10])

np.savez_compressed('vectors_test.npz', v1 = v1 , v2 = v2)

data = np.load('vectors_test.npz')

data1 = data['v1']
data2 = data['v2']

print(data1)
print(data2)

[1 2 3 4 5]
[ 6  7  8  9 10]


# Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values. 


In [101]:
v1 = np.random.randn(40)
v1

array([-0.6075477 , -0.12613641, -0.68460636,  0.92871475, -1.84440103,
       -0.46700242,  2.29249034,  0.48881005,  0.71026699,  1.05553444,
        0.0540731 ,  0.25795342,  0.58828165,  0.88524424, -1.01700702,
       -0.13369303, -0.4381855 ,  0.49344349, -0.19900912, -1.27498361,
        0.29349415,  0.10895031,  0.03172679,  1.27263986,  1.0714479 ,
        0.41581801,  1.55067923, -0.31137892, -1.37923991,  1.37140879,
        0.02771165, -0.32039958, -0.84617041, -0.43342892, -1.3370345 ,
        0.20917217, -1.4243213 , -0.55347685,  0.07479864, -0.50561983])

# 16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [105]:
v1 = np.array([10,20,30,40,50])

x_greater = v1>30
print(v1[x_greater])

x_lower = v1<30
print(v1[x_lower])

[40 50]
[10 20]


# DONE